[package]
name = "oci-storage-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
base64 = "0.22.1"
chrono = "0.4.42"
ini = "1.3.0"
openssl = "0.10.74" 
reqwest = "0.12.24"
tokio = { version = "1.48.0", features = ["full"] }
